---
driver:
  name: vagrant

provisioner:
  name: chef_zero

transport:
  name: winrm
  elevated: true

platforms:
  - name: windows2016

suites:
  - name: default
    run_list:
      - recipe[packer-templates::xwindows_update]
    attributes:
